version: '3.9'
services:
  social-network-api:
    build: .
    container_name: social-network-api
    ports:
      - "8085:8085"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: social-network-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
        - ./data:/data/db