version: '3.9'
services:
  social-network-api:
    build: .
    container_name: social-network-api
    ports:
      - "${PORT}:8085"
    env_file:
      - ".env"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo
    container_name: social-network-mongo
    env_file:
      - ".env"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
        - ./data:/data/db
    healthcheck:
      test: "exit 0"
      interval: 10s
      timeout: 5s
      retries: 5